// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Api.Migrations.Identity
{
    /// <inheritdoc />
    public partial class Add_RefreshTokens2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_refresh_token_users_user_id",
                schema: "identity",
                table: "refresh_token");

            migrationBuilder.DropPrimaryKey(
                name: "pk_refresh_token",
                schema: "identity",
                table: "refresh_token");

            migrationBuilder.RenameTable(
                name: "refresh_token",
                schema: "identity",
                newName: "refresh_tokens",
                newSchema: "identity");

            migrationBuilder.RenameIndex(
                name: "ix_refresh_token_user_id",
                schema: "identity",
                table: "refresh_tokens",
                newName: "ix_refresh_tokens_user_id");

            migrationBuilder.RenameIndex(
                name: "ix_refresh_token_token",
                schema: "identity",
                table: "refresh_tokens",
                newName: "ix_refresh_tokens_token");

            migrationBuilder.AddPrimaryKey(
                name: "pk_refresh_tokens",
                schema: "identity",
                table: "refresh_tokens",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_refresh_tokens_users_user_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "asp_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_refresh_tokens_users_user_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropPrimaryKey(
                name: "pk_refresh_tokens",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.RenameTable(
                name: "refresh_tokens",
                schema: "identity",
                newName: "refresh_token",
                newSchema: "identity");

            migrationBuilder.RenameIndex(
                name: "ix_refresh_tokens_user_id",
                schema: "identity",
                table: "refresh_token",
                newName: "ix_refresh_token_user_id");

            migrationBuilder.RenameIndex(
                name: "ix_refresh_tokens_token",
                schema: "identity",
                table: "refresh_token",
                newName: "ix_refresh_token_token");

            migrationBuilder.AddPrimaryKey(
                name: "pk_refresh_token",
                schema: "identity",
                table: "refresh_token",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_refresh_token_users_user_id",
                schema: "identity",
                table: "refresh_token",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "asp_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
